name: tailnflows 
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=1.13.1
  - jupyter
  - matplotlib
  - numpy
  - scipy
  - tqdm
  - pandas
  - seaborn
  - statsmodels
  - xarray
  - bottleneck
  - dask
  - netCDF4
  - pip>=3.0.0
  - pip:
    - posteriordb
    - git+https://github.com/Tennessee-Wallaceh/nflows
    - git+https://github.com/Tennessee-Wallaceh/marginalTailAdaptiveFlow